# Generated by Django 3.1.5 on 2021-02-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='defectiveness_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('defective_parts', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('report_datetime', models.DateTimeField(auto_now=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operator.bike')),
            ],
        ),
    ]
