# Generated by Django 3.1.5 on 2021-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('date_joined', models.TimeField()),
                ('last_login', models.TimeField()),
                ('role', models.CharField(max_length=10)),
                ('is_admin', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('hires_in_progress', models.IntegerField()),
                ('wallet_balance', models.FloatField()),
                ('amountz_owed', models.FloatField()),
            ],
        ),
    ]
