# Generated by Django 3.1.5 on 2021-02-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_account',
            old_name='amountz_owed',
            new_name='amount_owed',
        ),
    ]
