# Generated by Django 3.1.5 on 2021-02-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210206_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_account',
            name='amount_owed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='account_account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account_account',
            name='hires_in_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account_account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account_account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account_account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account_account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account_account',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account_account',
            name='role',
            field=models.CharField(default='User', max_length=10),
        ),
        migrations.AlterField(
            model_name='account_account',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
