# Generated by Django 3.1.5 on 2021-02-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0003_defectiveness_report_operator_id'),
        ('User', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start',
        ),
        migrations.AddField(
            model_name='order',
            name='check_out_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='end_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_station', to='Operator.station'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_station', to='Operator.station'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
